#!/bin/bash

if [[ "$1" == "-h" || "$1" == "--help" ]]; then
    echo "Usage: depcheck repo_name [optional: custom yum.conf]"
	echo "Example: depcheck centos7-rutgers-testing-temp"
	exit 0
fi

if [[ $# -eq 2 && ! -f "$2" ]]; then
    echo "That file does not exist"
    exit 1
fi

source /etc/rutgers-repotools-2.cfg

input=$1
ver=${input//[^0-9]/}
error=false

echo "Checking Dependencies"

if [[ $ver -lt 7 ]]; then
    if [[ $# -eq 2 ]]; then
        repoclosure -t -r $1 --config=$YUMCNF --config=$2 \
            -l base$ver-32 -l updates$ver-32 -l extras$ver-32 \
            -l base$ver -l updates$ver -l extras$ver > $TMPRPL
    else
        repoclosure -t -r $1 --config=$YUMCNF \
            -l base$ver-32 -l updates$ver-32 -l extras$ver-32 \
            -l base$ver -l updates$ver -l extras$ver > $TMPRPL
    fi
else
    if [[ $# -eq 2 ]]; then
        repoclosure -t -r $1 --config=$YUMCNF --config=$2 \
            -l base$ver -l updates$ver -l extras$ver > $TMPRPL
    else
        repoclosure -t -r $1 --config=$YUMCNF \
            -l base$ver -l updates$ver -l extras$ver > $TMPRPL
    fi
fi

sed -n '/unresolved\ deps/{:a;n;/package:\ /b;p;ba}' $TMPRPL \
    > $URDEPS

touch $RDPROB

while read line; do
    grep -q -i $line $DPIGN
    if [[ "$?" != "0" ]]; then
        echo "Missing dependency: $line" > $RDPROB
        error=true
    fi
done < $URDEPS

if [ "$error" = true ]; then
    echo -e "\nDependency errors detected:"
    cat $RDPROB
    echo "\nOutput from repoclosure:"
    cat $TMPRPL
    echo -e ""
    exit 1
fi

rm $RDPROB
rm $TMPRPL
rm $URDEPS

echo "No Dependency errors found"

exit 0
