#!/bin/bash
keep=false
twoconf=false
for var in "$@"
do
    if [[ "$var" == "-h" || "$var" == "--help" ]]; then
        echo "Usage: depcheck repo_name [optional: custom yum.conf]"
	    echo "Example: depcheck centos7-rutgers-testing-temp"
        echo "Note: To use -k, add it after the rest otherwise the program will fail"
	    exit 0
    fi
    if [[ "$var" == "-k" ]]; then
        keep=true
    fi
done

if [[ $keep = false && $# -eq 2 && ! -f "$2" ]]; then
    echo "That file does not exist"
    exit 1
fi

if [[ $keep = false && $# -eq 2 && -f "$2" ]]; then
    twoconf=true
fi

if [[ $keep = true && $# -eq 3 && ! -f "$2" ]]; then
    echo "That file does not exist"
    exit 1
fi
if [[ $keep = true && $# -eq 3 && -f "$2" ]]; then
    twoconf=true
fi

source /etc/rutgers-repotools-2.cfg

input=$1
ver=${input//[^0-9]/}
error=false
extra_repos=""
if [[ $ver -lt 7 ]]; then
    if [[ $1 == *"testing"* ]]; then
        extra_repos="-l centos$ver-rutgers-current -l centos$ver-rutgers-current-32";
    fi

    if [[ $1 == *"unstable"* ]]; then
        extra_repos="-l centos$ver-rutgers-current -l centos$ver-rutgers-testing-current \
            -l centos$ver-rutgers-current-32 -l centos$ver-rutgers-testing-current-32";
    fi
else
    if [[ $1 == *"testing"* ]]; then
        extra_repos="-l centos$ver-rutgers-current";
    fi

    if [[ $1 == *"unstable"* ]]; then
        extra_repos="-l centos$ver-rutgers-current -l centos$ver-rutgers-testing-current";
    fi
fi

rm -r /var/tmp/yum-${USER}-*

echo "Checking Dependencies"

if [[ $ver -lt 7 ]]; then
    if [[ $twoconf = true ]]; then
        repoclosure -t -r $1 -r $1-32 --config=$YUMCNF --config=$2 \
            -l base$ver-32 -l updates$ver-32 -l extras$ver-32 \
            -l base$ver -l updates$ver -l extras$ver $extra_repos > $TMPRPL
    else
        repoclosure -t -r $1 -r $1-32 --config=$YUMCNF \
            -l base$ver-32 -l updates$ver-32 -l extras$ver-32 \
            -l base$ver -l updates$ver -l extras$ver $extra_repos > $TMPRPL
    fi
else
    if [[ $twoconf = true ]]; then
        repoclosure -t -r $1 --config=$YUMCNF --config=$2 \
            -l base$ver -l updates$ver -l extras$ver $extra_repos > $TMPRPL
    else
        repoclosure -t -r $1 --config=$YUMCNF \
            -l base$ver -l updates$ver -l extras$ver $extra_repos > $TMPRPL
    fi
fi

sed -n '/unresolved\ deps/{:a;n;/package:\ /b;p;ba}' $TMPRPL \
    > $URDEPS

touch $RDPROB

while read line; do
    grep -q -i "$line" $DPIGN
    if [[ "$?" != "0" ]]; then
        echo "Missing dependency: $line" >> $RDPROB
        error=true
    fi
done < $URDEPS

if [ "$error" = true ]; then
    echo -e "\nDependency errors detected:"
    cat $RDPROB
    echo "\nOutput from repoclosure:"
    cat $TMPRPL
    echo -e ""
    if [[ "$keep" = false ]]; then
        rm $RDPROB
        rm $TMPRPL
        rm $URDEPS
    fi
    exit 1
fi

if [[ "$keep" = false ]]; then
    rm $RDPROB
    rm $TMPRPL
    rm $URDEPS
fi

echo "No Dependency errors found"

exit 0
