#!/bin/bash
# koji_backup: Backs up the Koji database.
#
# This script is called by the daily_checks job and uses the Koji package
# directory and backup directory specified in the configuration file:
#
# [koji]
# pkgdir    = /usr/koji/packages
# backupdir = /usr/koji/backups
#
# You can also specify another directory by running it by hand in the command
# line.

if [ $# -ne 2 ]; then
    echo "Usage: koji-backup <koji-dir> <backup-dir>"
    exit 1
fi

# Exit on error
set -e

# Output an error message
function error() {
    echo "ERROR: $1"
}

# Check that temp directory is secure
eval dirpath="/var/run/rutgers-repotools-2"
if [ ! -d "$dirpath" ]; then
    error "$dirvar path is invalid: \"$dirpath\" is not a directory"
    exit 1
elif [ "drwx------" != "$(stat -c %A /var/run/rutgers-repotools-2)" ]; then
    error "$dirpath does not have correct (700) permissions"
    exit 1
elif [ "koji" != "$(stat -c %U /var/run/rutgers-repotools-2)" ]; then
    error "$dirpath is not owned by koji"
    exit 1
fi

# Dump Koji DB to local disk
echo "Dumping Koji database to disc..."
sudo -u koji sh -c "pg_dump -C koji -U koji > /var/run/rutgers-repotools-2/koji_dbdump.sql"

# Sync the backup to our backup location
echo "Syncing to backup location..."
rsync --archive --sparse --delete "$1" "$2/packages"
rsync --archive /var/run/rutgers-repotools-2/koji_dbdump.sql "$2"
sudo -u koji sh -c "rm -f /var/run/rutgers-repotools-2/koji_dbdump.sql"
echo "Backup complete!"
