#!/bin/bash

if [[ "$1" == "-h" || "$1" == "--help" ]]; then
	echo "Usage: pullpackage [koji tag] [RPM name in nvr format]"
	echo "Example: pullpackage centos6-rutgers-testing test-3.0-2.ru6"
	exit 0
fi

if [[ $EUID -eq 0 ]]; then
	echo "Error: Do not run this script as root" 1>&2
	exit 1
fi

if ! id -nG "$USER" | grep -qw "packagepushers"; then
  echo "ERROR: $USER does not belong to packagepushers"
  exit 1
fi

source /etc/rutgers-repotools-2.cfg

if [[ ! -f "$MASHD$1.mash" ]]; then
	echo "There is no mash file for that repo"
	exit 1
fi

if [[ -f "$LOCK" ]]; then
    echo "Operation on repository already occurring, try again later"
    exit 1
fi

touch $LOCK

echo "Untagging packages"
for var in "$@"
do
    # probably don't need an if to skip first arg, but too lazy to find another
    # way lol
    if [[ $var -ne $1 ]]; then
        koji untag-pkg $1 $var
        if [[ "$?" != "0" ]]; then
	        echo "Failed to untag package $var!"
            rm $LOCK
	        exit 1
        fi
    fi
done

echo "Called rebuild-repo"
rebuild-repo $1 -k -nolock
if [[ "$?" != "0" ]]; then
	echo "Rebuild-Repo failed!! Retagging package and exiting..."
    for var in "$@"
    do
        # probably don't need an if to skip first arg, but too lazy to find another
        # way lol
        if [[ $var -ne $1 ]]; then
            koji tag-pkg $1 $var
            if [[ "$?" != "0" ]]; then
	            echo "Failed to tag package $var!"
            fi
        fi
    done
    echo "Sending Mail"
    echo -e "Pullpackage failed with the following output:\n\nDependency Errors detected:\n$(cat $RDPROB)\n\nOutput from repoclosure:\n$(cat $TMPRPL)" | \
        mailx -r "roji@koji.rutgers.edu" -s "CentOS Broken Dependencies" "$EMAIL"
    rm $RDPROB
    rm $TMPRPL
    rm $URDEPS
    rm $LOCK
	exit 1
fi

echo "Sending email(s)"
for var in "$@"
do
    # probably don't need an if to skip first arg, but too lazy to find another
    # way lol
    if [[ $var -ne $1 ]]; then
        echo -e "Pushpackage successfully pulled $var to $1 along with its breakout packages" | \
            mailx -r "roji@koji.rutgers.edu" -s "CentOS Pull Successful - $var" "$EMAIL"
        if [[ "$?" != "0" ]]; then
	        echo "Failed to send email for package $var"
        fi
    fi
done

rm $RDPROB
rm $TMPRPL
rm $URDEPS
rm $LOCK

echo "Successfully pulled package!"
exit 0
