#!/bin/bash
MASHD="/etc/mash/"

if [[ "$1" == "-h" || "$1" == "--help" ]]; then
	echo "Usage: pushpackage [koji tag] [RPM name in nvr format]"
	echo "Example: pushpackage centos6-rutgers-testing test-3.0-2.ru6"
	exit 0
fi

if [[ $EUID -ne 0 ]]; then
	echo "This script must be run as root" 1>&2
	exit 1
fi

source /etc/rutgers-repotools-2.cfg

if [[ ! -f "$MASHD$1.mash" ]]; then
	echo "There is no mash file for that repo"
	exit 1
fi

echo "Tagging packages"
koji tag-pkg $1 $2

if [[ "$?" != "0" ]]; then
	echo "Failed to tag packages!"
	exit 1
fi

echo "Called rebuild-repo"
./rebuild-repo $1
if [[ "$?" != "0" ]]; then
	echo "Rebuild-Repo failed!! Untagging packages and exiting..."
	koji untag-pkg $1 $2
	exit 1
fi

echo "Successfully pushed package!"
exit 0
