#!/bin/bash

if [[ "$1" == "-h" || "$1" == "--help" ]]; then
	echo "Usage: rebuild-repo [koji tag]"
	echo "Example: rebuild-repo centos6-rutgers-testing"
	exit 0
fi

if [[ $EUID -ne 0 ]]; then
	echo "This script must be run as root" 1>&2
	exit 1
fi

source /etc/rutgers-repotools-2.cfg

if [[ ! -f "$MASHD$1.mash" ]]; then
	echo "There is no mash file for that repo"
	exit 1
fi


if [[ -f "$LOCK" ]]; then
    echo "Operation on repository alreeady occurring, try again later"
    exit 1
fi

touch $LOCK

# From Koji Set-up Guide: Kojira may need to be restarted when new tags are
# added in order to detect those tags correctly.
echo "Restarting kojira"
service kojira restart

if [[ -d "$TMPD" ]]; then
	echo "Deleteing old temp repository"
	rm -r $TMPD
fi

if [[ -d "$TGTD$1" ]]; then
	echo "Deleteing bad repository"
	rm -r $TGTD$1
fi

echo "Commence the mashing!"

mash -o $TGTD $1

if [[ "$?" != "0" ]]; then
	echo "Mash failed to generate the repo"
	echo "Deleteing bad repository"
	rm -r ${TGTD}$1
    rm $LOCK
	exit 1
fi

echo "Mash successfully generated the repository"

./depcheck.sh $1 -k

rm $RDPROB
rm $TMPRPL
rm $URDEPS

if [[ "$?" != "0" ]]; then
    echo "Exiting due to dependency errors..."
    rm $LOCK
    exit 1
fi

echo "Switching repo directory names"

if [[ -d "$ACTD" ]]; then
	mv $ACTD $TMPD
fi

mv $TGTD$1 $ACTD

if [[ "$?" != "0" ]]; then
	echo "FAILED TO SWITCH REPO NAMES: PLEASE FIX MANUALLY"
    rm $LOCK
	exit 1
fi

rm $LOCK

echo "Successfully regenerated repo!"
exit 0
