#!/bin/bash
nodep=false
nolock=false
keep=false
for var in "$@"
do
    if [[ "$var" == "-h" || "$var" == "--help" ]]; then
	    echo "Usage: rebuild-repo [koji tag]"
	    echo "Example: rebuild-repo centos6-rutgers-testing"
	    exit 0
    fi
    if [[ "$var" == "-nodep" ]]; then
        nodep=true
    fi
    if [[ "$var" == "-nolock" ]]; then
        nolock=true
    fi
    if [[ "$var" == "-k" ]]; then
        keep=true
    fi
done

if [[ $EUID -eq 0 ]]; then
	echo "Error: Do not run this script as root" 1>&2
	exit 1
fi

if ! id -nG "$USER" | grep -qw "packagepushers"; then
  echo "ERROR: $USER does not belong to packagepushers"
  exit 1
fi

source /etc/rutgers-repotools-2.cfg

if [[ ! -f "$MASHD$1.mash" ]]; then
	echo "There is no mash file for that repo"
	exit 1
fi

if [[ $nolock = false ]]; then
    if [[ -f "$LOCK" ]]; then
        echo "Operation on repository already occurring, try again later"
        exit 1
    fi
    touch $LOCK
fi

# From Koji Set-up Guide: Kojira may need to be restarted when new tags are
# added in order to detect those tags correctly.
# echo "Restarting kojira"
# service kojira restart

if [[ -d "$TMPD" ]]; then
	echo "Deleting old temp repository"
	rm -rf $TMPD
fi

if [[ -d "$TGTD$1" ]]; then
	echo "Deleting bad repository"
	rm -rf $TGTD$1
fi

echo "Commence the mashing!"

mash -o $TGTD $1

rm -rf /var/tmp/mash

if [[ "$?" != "0" ]]; then
	echo "Mash failed to generate the repo"
    if [[ $nolock = false ]]; then
        rm $LOCK
    fi
	exit 1
fi

echo "Mash successfully generated the repository"

if [[ $nodep = false ]]; then
    depcheck $1 -k

    if [[ "$?" != "0" ]]; then
        echo "Exiting due to dependency errors..."
        if [[ $keep = false  ]]; then
            rm $RDPROB
            rm $TMPRPL
            rm $URDEPS
        fi
        if [[ $nolock = false ]]; then
            rm $LOCK
        fi
        exit 1
    fi

    if [[ $keep = false ]]; then
        rm $RDPROB
        rm $TMPRPL
        rm $URDEPS
    fi
fi

echo "Switching repo directory names"

if [[ -d "$ACTD" ]]; then
	mv $ACTD $TMPD
fi

mv $TGTD$1 $ACTD

if [[ "$?" != "0" ]]; then
	echo "FAILED TO SWITCH REPO NAMES: PLEASE FIX MANUALLY"
    if [[ $nolock = false ]]; then
        rm $LOCK
    fi
	exit 1
fi

echo "Setting correct group and permissions"
find $ACTD -type d -exec chown $USER:packagepushers {} +
if [[ "$?" != "0" ]]; then
	echo "FAILED TO SET NEW OWNER PERMISSIONS: PLEASE FIX MANUALLY"
    if [[ $nolock = false ]]; then
        rm $LOCK
    fi
	exit 1
fi

find $ACTD -type d -exec chmod 775 {} +
if [[ "$?" != "0" ]]; then
	echo "FAILED TO CHMOD 775 ON $ACTD: PLEASE FIX MANUALLY"
    if [[ $nolock = false ]]; then
        rm $LOCK
    fi
	exit 1
fi

if [[ $nolock = false ]]; then
    rm $LOCK
fi

echo "Successfully regenerated repo!"
exit 0
